# Generated by Django 6.0.7 on 2026-07-21 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80, verbose_name='action')),
                ('object_type', models.CharField(blank=True, max_length=100, verbose_name='type d’objet')),
                ('object_id', models.CharField(blank=True, max_length=80, verbose_name='identifiant')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'entrée du journal',
                'verbose_name_plural': 'journal des actions',
                'ordering': ['-created_at'],
            },
        ),
    ]
