# Generated by Django 6.0.7 on 2026-07-20 23:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscribers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('subject', models.CharField(max_length=200, verbose_name='objet de l’e-mail')),
                ('summary', models.TextField(max_length=500, verbose_name='résumé')),
                ('content', models.TextField(verbose_name='contenu')),
                ('cta_label', models.CharField(blank=True, max_length=80, verbose_name='libellé du bouton')),
                ('cta_url', models.URLField(blank=True, verbose_name='lien du bouton')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publiée')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publiée le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='nom')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sending', 'En cours'), ('sent', 'Envoyée'), ('failed', 'Échec')], default='draft', max_length=20)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='subscribers.segment')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='newsletters.newsletter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('failed', 'Échec')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='newsletters.campaign')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='subscribers.subscriber')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('campaign', 'subscriber'), name='unique_campaign_delivery')],
            },
        ),
    ]
