# Generated by Django 6.0.7 on 2026-07-21 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created_at'], 'permissions': [('send_campaign', 'Peut envoyer et planifier une campagne')]},
        ),
        migrations.AddField(
            model_name='campaign',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='envoi planifié'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='test_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Planifiée'), ('sending', 'En cours'), ('sent', 'Envoyée'), ('failed', 'Échec'), ('cancelled', 'Annulée')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('open', 'Ouverture'), ('click', 'Clic')], max_length=20)),
                ('target_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='newsletters.delivery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
