# Generated by Django 6.0.7 on 2026-07-20 23:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse e-mail')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='prénom')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='nom')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('active', 'Actif'), ('unsubscribed', 'Désinscrit')], default='pending', max_length=20)),
                ('consent', models.BooleanField(default=False, verbose_name='consentement')),
                ('consented_at', models.DateTimeField(blank=True, null=True, verbose_name='consentement donné le')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmé le')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='désinscrit le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('confirmation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'abonné',
                'verbose_name_plural': 'abonnés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nom')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscribers', models.ManyToManyField(blank=True, related_name='segments', to='subscribers.subscriber')),
            ],
            options={
                'verbose_name': 'segment',
                'verbose_name_plural': 'segments',
                'ordering': ['name'],
            },
        ),
    ]
