# Generated by Django 6.0.7 on 2026-07-21 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='rule',
            field=models.CharField(choices=[('manual', 'Sélection manuelle'), ('active', 'Tous les abonnés actifs'), ('recent', 'Abonnés récents'), ('opened', 'Ayant ouvert une campagne'), ('never_opened', 'N’ayant jamais ouvert')], default='manual', max_length=30),
        ),
        migrations.AddField(
            model_name='segment',
            name='rule_campaign_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='campagne'),
        ),
        migrations.AddField(
            model_name='segment',
            name='rule_days',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='nombre de jours'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='anonymisé le'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='source',
            field=models.CharField(choices=[('public', 'Formulaire public'), ('manual', 'Ajout manuel'), ('import', 'Import CSV')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('subscribed', 'Inscription'), ('confirmed', 'Confirmation'), ('unsubscribed', 'Désinscription'), ('imported', 'Import CSV'), ('updated', 'Modification'), ('anonymized', 'Anonymisation')], max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='subscribers.subscriber')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
